Update installation script

diff --git a/scripts/guest/m-reinstall b/scripts/guest/m-reinstall
--- a/scripts/guest/m-reinstall
+++ b/scripts/guest/m-reinstall
@@ -91,16 +91,16 @@ install_cmd="./bin/magento setup:install \
     --use-rewrites=1"
 
 # Configure Rabbit MQ
-#if [[ -d "${MAGENTO_ROOT}/app/code/Magento/MessageQueue" ]] || [[ -d "${MAGENTO_ROOT}/vendor/magento/module-message-queue" ]]; then
-#    install_cmd="${install_cmd} \
-#    --amqp-host=${setupOptions[amqp_host]} \
-#    --amqp-port=${setupOptions[amqp_port]} \
-#    --amqp-user=${setupOptions[amqp_user]} \
-#    --amqp-virtualhost=${setupOptions[amqp_virtualhost]} \
-#    --amqp-ssl=false \
-#    --amqp-ssl-options=[] \
-#    --amqp-password=${setupOptions[amqp_password]}"
-#fi
+if [[ -d "${MAGENTO_ROOT}/app/code/Magento/MessageQueue" ]] || [[ -d "${MAGENTO_ROOT}/vendor/magento/module-message-queue" ]]; then
+    install_cmd="${install_cmd} \
+    --amqp-host=${setupOptions[amqp_host]} \
+    --amqp-port=${setupOptions[amqp_port]} \
+    --amqp-user=${setupOptions[amqp_user]} \
+    --amqp-virtualhost=${setupOptions[amqp_virtualhost]} \
+    --amqp-ssl=false \
+    --amqp-ssl-options=[] \
+    --amqp-password=${setupOptions[amqp_password]}"
+fi
 
 # TODO: Permission denied
 #sudo chmod +x bin/magento
@@ -110,52 +110,52 @@ php ${install_cmd}
 # Comment out the line above and uncomment the one below to debug Magento Setup script
 # php -d xdebug.remote_autostart=1 ${install_cmd} 2> >(logError) > >(log)
 
-#status "Configuring Redis for session and as cache backend"
-#php "${MAGENTO_ROOT}/bin/magento" setup:config:set --page-cache=redis --page-cache-redis-server=magento2-redis-master
-#php "${MAGENTO_ROOT}/bin/magento" setup:config:set --cache-backend=redis --cache-backend-redis-server=magento2-redis-master
-#php "${MAGENTO_ROOT}/bin/magento" setup:config:set --session-save=redis --session-save-redis-host=magento2-redis-master
+status "Configuring Redis for session and as cache backend"
+php "${MAGENTO_ROOT}/bin/magento" setup:config:set --page-cache=redis --page-cache-redis-server=magento2-redis-master
+php "${MAGENTO_ROOT}/bin/magento" setup:config:set --cache-backend=redis --cache-backend-redis-server=magento2-redis-master
+php "${MAGENTO_ROOT}/bin/magento" setup:config:set --session-save=redis --session-save-redis-host=magento2-redis-master
 
 if [[ $? != 0 ]]; then
     error "Magento installation failed."
     exit 1
 fi
 
-#bash "${devbox_dir}/scripts/guest/configure_varnish" -f
+bash "${devbox_dir}/scripts/guest/configure_varnish" -f
 
 # TODO: Remove
 #if [[ ${is_windows_host} == 1 ]] || [[ ${use_nfs} == 0 ]]; then
 #    status "Changing ownership of "${MAGENTO_ROOT}" to devbox:devbox"
-#    sudo chown -R devbox:devbox ${MAGENTO_ROOT}
+#    sudo chown -R devbox:devbox ${MAGENTO_ROOT}tests/include/helpers.sh
 #fi
 
-#bash "${DEVBOX_ROOT}/scripts/guest/configure_search_engine"
-#bash "${DEVBOX_ROOT}/scripts/guest/change_magento_config_for_functional_tests"
-#bash "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'admin/security/session_lifetime' '86400'
+bash "${DEVBOX_ROOT}/scripts/guest/configure_search_engine"
+bash "${DEVBOX_ROOT}/scripts/guest/change_magento_config_for_functional_tests"
+bash "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'admin/security/session_lifetime' '86400'
 
-#export SKIP_CACHE_CLEAN=0
-#bash "${DEVBOX_ROOT}/scripts/guest/m-clear-cache"
+export SKIP_CACHE_CLEAN=0
+bash "${DEVBOX_ROOT}/scripts/guest/m-clear-cache"
 
-#if [[ ${generate_basic_data} != 0 ]]; then
-#    bash "${DEVBOX_ROOT}/scripts/guest/generate_basic_data"
-#fi
+if [[ ${generate_basic_data} != 0 ]]; then
+    bash "${DEVBOX_ROOT}/scripts/guest/generate_basic_data"
+fi
 
 status "Checking if Magento frontend is accessible at '${setupOptions[base_url]}'"
 magento_home_page_content="$(curl -sL ${setupOptions[base_url]})"
 pattern="All rights reserved."
-#if [[ ${magento_home_page_content} =~ ${pattern} ]]; then
-#
-#    bash "${DEVBOX_ROOT}/scripts/guest/warm_up_cache"
-#
-#    status "Generating XSD references for PHP Storm in the background"
-#    php "${MAGENTO_ROOT}/bin/magento" dev:urn-catalog:generate "${devbox_dir}/.idea/misc.xml" && sed -i "s|${MAGENTO_ROOT}|${MAGENTO_ROOT_HOST}|g" "${devbox_dir}/.idea/misc.xml" &
-#
-#    decrementNestingLevel
-#    success "Magento reinstalled successfully"
-#    info "$(regular)Magento application was deployed to $(bold)${MAGENTO_ROOT}$(regular) and installed successfully
-#
-#    Access storefront at $(bold)${setupOptions[base_url]}$(regular)
-#    Access admin panel at $(bold)${setupOptions[base_url]}${setupOptions[admin_frontname]}/$(regular)"
-#else
-#    error "Magento frontend is not accessible at '${setupOptions[base_url]}' after installation. Please scan output above and logs for errors"
-#    exit 1
-#fi
+if [[ ${magento_home_page_content} =~ ${pattern} ]]; then
+
+    bash "${DEVBOX_ROOT}/scripts/guest/warm_up_cache"
+
+    status "Generating XSD references for PHP Storm in the background"
+    php "${MAGENTO_ROOT}/bin/magento" dev:urn-catalog:generate "${devbox_dir}/.idea/misc.xml" && sed -i "s|${MAGENTO_ROOT}|${MAGENTO_ROOT_HOST}|g" "${devbox_dir}/.idea/misc.xml" &
+
+    decrementNestingLevel
+    success "Magento reinstalled successfully"
+    info "$(regular)Magento application was deployed to $(bold)${MAGENTO_ROOT}$(regular) and installed successfully
+
+    Access storefront at $(bold)${setupOptions[base_url]}$(regular)
+    Access admin panel at $(bold)${setupOptions[base_url]}${setupOptions[admin_frontname]}/$(regular)"
+else
+    error "Magento frontend is not accessible at '${setupOptions[base_url]}' after installation. Please scan output above and logs for errors"
+    exit 1
+fi
